name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've also considered...

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide code examples or mockups if applicable
      render: typescript
      placeholder: |
        // Example usage
        const result = await api.newFeature()

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to implement this feature?
      options:
        - label: I would like to implement this feature
        - label: I would like to help with testing
        - label: I would like to help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
